import AuthProvider from '@/components/AuthProvider';
import Navbar from '@/components/Navbar';
import TestSession from '@/components/TestSession';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<AuthProvider>
					<TestSession />
					<Navbar />
					<div className="flex pt-16">{children}</div>
				</AuthProvider>
			</body>
		</html>
	);
}
